discovery:
  image: t1m1/discovery-server
  restart: always
  ports:
    - "8761:8761"

mongo-user:
  image: mongo:3.0
  command: "--smallfiles"
  ports:
    - "1001:27017"
  restart: always

mongo-message:
  image: mongo:3.0
  command: "--smallfiles"
  ports:
    - "1002:27017"
  restart: always
  
mongo-document:
  image: mongo:3.0
  command: "--smallfiles"
  ports:
    - "1003:27017"
  restart: always
  
user:
  image: t1m1/user
  restart: always
  links:
    - mongo-user
    - discovery

message:
  image: t1m1/message
  restart: always
  links:
    - mongo-message
    - discovery

document:
  image: t1m1/document
  restart: always
  links:
    - mongo-document
    - discovery

mailbox:
  image: t1m1/mailbox
  restart: always
  links:
    - discovery

dashboard:
  image: t1m1/dashboard
  restart: always
  ports:
    - "8383:8383"
  links:
    - mailbox

edge:
  image: t1m1/edge-server
  restart: always
  ports:
    - "1111:1111"
  links:
    - discovery

web:
  image: t1m1/web
  restart: always
  ports:
    - "8080:8080"
  links:
    - edge