# wenn VCAP_APPLICATION_PORT Umgebungsvariable nicht verfügbar -> default Port 8761
server:
  port: ${PORT:8761}

 # Teilt der Instanz mit, sich nicht "bei sich selber" zu registrieren
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0   
---

spring:
  profiles: local1
server:
  port: 8761
eureka:
  instance:
    hostname: local1
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka
---

spring:
  profiles: local2
server:
  port: 8762
eureka:
  instance:
    hostname: local2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka