# use any port - dynamic
server:
  port: 0

spring:
  data:
    mongodb:
      host: localhost
      port: 1003
      
# 'leaseRenewalIntervalInSeconds' - beschleunigt den Prozess das ein Services sich beim Eureka anmeldet
# 'instanceId' für die eindeutige identifizierung eines Services - Eureka Dashboard
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}


---
# For deployment in Docker containers
spring:
  profiles: docker
  data:
    mongodb:
      host: mongo-document
      port: 27017

server:
  port: 8080
        
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
