# use any port - dynamic
server:
  port: 0

# 'leaseRenewalIntervalInSeconds' - beschleunigt den Prozess das ein Services sich beim Eureka anmeldet

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}