# use any port - dynamic
server:
  port: 0

spring:
  data:
    mongodb:
      host: localhost
      port: 1001
      
# 'leaseRenewalIntervalInSeconds' - beschleunigt den Prozess das ein Services sich beim Eureka anmeldet
# 'instanceId' - für die eindeutige identifizierung eines Services - Eureka Dashboard
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
