FROM    centos:centos6

# Enable EPEL for Node.js
RUN     rpm -Uvh http://download.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm

# Install Node.js and npm
RUN     yum install -y npm

# Bundle app source
COPY . /
# Install app dependencies
RUN npm install

ENV HOST '192.168.99.100'

EXPOSE  8080
CMD ["node", "/server.js"]